Sources/FileSystem/FileSystem.swift

When using `FileSystem`, I've noticed the `copy` signature in the `FileSysteming` protocol is not accurate (it is accurate in the `FileSystem` itself, however).

Update copy function signature

---

Sources/FileSystem/FileSystem.swift
Tests/FileSystemTests/FileSystemTests.swift

As of now, `resolveSymbolicLink` throws an error if the passed path is not a symbolic link.
For `tuist/tuist` purposes, we often don't know if a given path is or is not symbolic link since it depends on the user input or specific `xcodebuild` behavior.
I believe it's better to simply return the path without resolving if the file/directory is _not_ a symlink instead of throwing. 
Alternatively, we could add an `isSymbolicLink` method and let the consumers of the library ensure `resolveSymbolicLink` is called only for actual symlinks. But in `tuist/tuist`, we would have to do this dance almost everywhere we end up using `resolveSymbolicLink`, which is why I'm leaning to the former.

fix: do not throw error when resolving symlink of a plain directory

---

Package.resolved
Package.swift
Tests/FileSystemTests/FileSystemTests.swift

Moved to a fork until this [fix](https://github.com/davbeck/swift-glob/pull/14) is merged.

Fix glob returning paths with resolved symlinks

---

.github/workflows/file-system.yml
Sources/FileSystem/AbsolutePath+Extras.swift
Sources/FileSystem/FileManager+Extras.swift
Sources/FileSystem/FileSystem.swift
Sources/FileSystem/Glob.swift
Tests/FileSystemTests/FileSystemTests.swift

The [swift-glob](https://github.com/davbeck/swift-glob) library that we decided to use is currently not production ready. There are a bunch of issues that need to be fixed before we rely on it in `tuist/tuist`. I will try to open PRs and issues to eventually still migrate to it. The issues I ran into so far:
- `glob(directory: "some-dir", include: ["."])` doesn't return anything when it should return `some-dir` if it exists. The same when include is `[""]`
- `glob(directory: "/", include: ["var/..../app"])` actually goes through literally every single directory on your system when it should first find a pivot and go through directories from there
- The library shouldn't returned paths with resolved symlinks: https://github.com/davbeck/swift-glob/pull/14
- `glob(directory: "some-dir", …

feat: use different implementation of globbing for more stable behavior

---

.github/workflows/conventional-pr.yml

PRs don't get released if the commits don't align with the conventional commits convention. I'm adding a check, so this doesn't happen in a future.

chore: add conventional PR check

---

Sources/FileSystem/FileSystem.swift
Tests/FileSystemTests/FileSystemTests.swift

Aligning with the previous implementation of globbing that included hidden files by default.

fix: include hidden files by default

---

Package.resolved
Package.swift
Tests/FileSystemTests/FileSystemTests.swift

Searching for files through directory symlinks wouldn't find those. The updated version of `swift-glob` has a fix for this.

fix: searching for files in symlinked directories

---

Package.resolved
Package.swift
Sources/FileSystem/FileSystem.swift
Tests/FileSystemTests/FileSystemTests.swift

Fixes issue flagged in: https://github.com/tuist/tuist/issues/6979

fix: matching files with double globstar

---

Package.resolved
Package.swift
Tests/FileSystemTests/FileSystemTests.swift

Fix matching file directly in a directory with a pattern such as `**/name-of-file.swift`

fix: path wildcard with constant component

---

Package.resolved
Package.swift
Project.swift
Sources/Glob/GlobSearch.swift
Sources/Glob/InvalidPattern.swift
Sources/Glob/Pattern+Match.swift
Sources/Glob/Pattern+Options.swift
Sources/Glob/Pattern+Parser.swift
Sources/Glob/Pattern.swift
Sources/Glob/Unicode.GeneralCategory+Helpers.swift
Tests/GlobTests/PatternTests.swift
Tests/GlobTests/TestHelpers/XCTAssertMatches.swift
Tests/GlobTests/TestHelpers/XCTExpectFailure.swift

We have been more and more diverging from the original [swift-glob](https://github.com/davbeck/swift-glob) library to align with the behavior we need in `tuist/tuist`. That work has been happening in our fork: https://github.com/tuist/swift-glob
Fixing issues in our `swift-glob` meant having to update `swift-glob`, `FileSystem`, and only then update the `FileSystem` in `tuist/tuist`. To simplify the setup, we're importing the necessary subset of `swift-glob` and we're taking full ownership of that part of the library.

refactor: migrate used subset of swift-glob to FileSystem

---

Sources/Glob/GlobSearch.swift
Tests/FileSystemTests/FileSystemTests.swift

Related: https://github.com/tuist/tuist/issues/6981
As flagged in the attached issue, the `glob` method fails when the base directory is a symlink. The initial [attempt](https://github.com/tuist/FileSystem/pull/78) to fix the issue would handle symlinks only when they appeared as we go through the nested directories.

fix: glob when base directory is a symlink

---

Sources/FileSystem/FileSystem.swift
Tests/FileSystemTests/FileSystemTests.swift

Related: https://github.com/tuist/tuist/issues/6991
`.DS_Store` should be excluded by default.

fix: ignore .DS_Store results when globbing

---

Sources/FileSystem/FileSystem.swift
Tests/FileSystemTests/FileSystemTests.swift

As flagged in https://github.com/apple/swift-nio/issues/2933, the `NIOFileSystem` removal performance is abysmal. Ideally, we'd do a fix in `swift-nio`, but for now, the quicker solution is to move to `FileManager`.

fix: use FileManager for file and directory removal to fix performance issues

---

Sources/FileSystem/FileSystem.swift
Tests/FileSystemTests/FileSystemTests.swift

When updating `FileSystem` in `tuist/tuist`, I noticed that the new `remove` implementation throws when deleting a file that doesn't exist – unlike the original `swift-nio` implementation.

fix: removing non-existing file or directory

---

Sources/FileSystem/FileSystem.swift
Tests/FileSystemTests/FileSystemTests.swift

Related: https://github.com/tuist/tuist/issues/7026
This PR fixes matching files with options such as `*.{swift,cpp}`. In case there are multiple option groups, we currently expand only one which is a known limitation. To fix that, we'd need to match each option with all options from all other option groups, increasing the complexity of this PR (and the O(n)) complexity considerably.

fix: glob with extension options

---

Sources/Glob/GlobSearch.swift

Related: https://github.com/tuist/tuist/issues/7053
Updates the condition for when we search recursively to not do so when we have a glob such as `*.xcworkspace`. We still need to search through nested directories in cases like `*/*.xcworkspace`. Ideally, we count the number of directory wildcards and go only as deep as we possibly need to go – instead of going recursively as we do now.

fix: do not search recursively when a glob is a file name wildcard

---

Sources/FileSystem/FileSystem.swift

When `move` is run concurrently, we could try to make a directory that already exists. As a hotfix, we're ignoring the error. If the directory was not created, the following line when moving the file would fail, so we're not fully ignoring this error.

fix: recreating directory when on concurrent move

---

Sources/FileSystem/FileSystem.swift
Sources/Glob/GlobSearch.swift
Tests/FileSystemTests/FileSystemTests.swift
Tuist.swift

This should fix https://github.com/tuist/tuist/issues/7145. There may be other or better ways to fix this. But the root issue seems to be handling of an relative symbolic link.

feat: handle relative symbolic links

---

Package.resolved
Package.swift

The https://github.com/tuist/FileSystem/pull/103 PR updated `ZIPFoundation` to an unstable version to fix compilation issues on Linux. However, unstable versions cause issues for consumers. In general, it's better to use a fork with a new version of a library instead.

fix: unstable ZIPFoundation version

---

Package.resolved
Sources/FileSystem/FileSystem.swift

I accidentally commented out this piece of code in https://github.com/tuist/FileSystem/pull/103 as pointed by @ajkolean: https://github.com/tuist/FileSystem/pull/103#discussion_r1942239432
I'm bringing it back behind a `macOS` compiler directive.

fix: temporary directory to return direct path instead of symlink

---

Package.resolved
Sources/FileSystem/FileSystem.swift

I noticed when using `fileSystem.inTemporaryDirectory` we always pass the same value to `prefix`, `UUID().uuidString`, so I extended the `FileSysteming` extension to pass it by default.

feat: add defaults to the `inTemporaryDirectory` to improve the convenience of the API

---

.github/workflows/file-system.yml
.github/workflows/release.yml
.mise/tasks/build-linux
.mise/tasks/test-linux
Sources/FileSystem/FileSystemTestingTrait.swift
Tests/FileSystemTests/FileSystemTestingTraitTests.swift

Drawing inspiration from `ExUnit.Case` [tmp dir](https://hexdocs.pm/ex_unit/main/ExUnit.Case.html#module-tmp-dir) tag, I'm adding a custom Swift Testing trait to create a temporary directory and scope its lifecycle to the test ore suite's.
```swift
@Test(.inTemporaryDirectory) func exampleTest() async throws {
let temporaryDirectory = try #require(FileSystem.testTemporaryDirectory)
}
```

feat: add a Swift Testing trait to create and scope a temporary directory to a test or suite lifecycle

---

Package.swift

It's not necessarily designed to be used directly, but Glob is pretty handy to use on its own in some cases, so wondering if you would be willing to expose it as its own package product 🙏

feat: expose Glob target as a package product

---

.github/workflows/conventional-pr.yml
Package.resolved
Sources/FileSystem/FileSystem.swift
Tests/FileSystemTests/FileSystemTests.swift

While [solving](https://github.com/tuist/tuist/pull/7907) the race condition with auth in Tuist, I came across to detect if a lockfile is present but old, and I realized we don't have an API for that in FileSystem, so I'm adding it.

feat:  add API to get the metadata of a particular file

---

Package.resolved
Package.swift
Sources/FileSystem/FileSystem.swift

`swift-nio` removed the `NIOFileSystem` from products in favor of `_NIOFileSystem` while they are finessing the API 🙃 
https://github.com/apple/swift-nio/pull/3370

feat: update swift-nio
